#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Run ncmpcpp with alternate config

# bspwm directory
DIR="$HOME/.config"

CONFIG="$DIR/alacritty/alacritty.toml"

alacritty --class 'alacritty-float,alacritty-float' --config-file "$CONFIG" \
  -o window.dimensions.columns=140 window.dimensions.lines=40 \
  -e ncmpcpp
#kitty --class 'kitty-float' --config ~/.config/kitty/kitty.conf -o initial_window_width=105 -o initial_window_height=22 -e ncmpcpp
